CREATE TABLE CABS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    DRIVER_NAME VARCHAR(100),
    TOTAL_SEATS INT NOT NULL,
    LUGGAGE_CAPACITY INT NOT NULL,
    CURRENT_LAT DOUBLE NOT NULL,
    CURRENT_LNG DOUBLE NOT NULL,
    CURRENT_GEOHASH VARCHAR(12) NOT NULL,
    STATUS VARCHAR(20) NOT NULL,
    VERSION BIGINT DEFAULT 0,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,

    INDEX IDX_CAB_STATUS (status),
    INDEX IDX_CURRENT_GEOHASH (current_geohash)
)