CREATE TABLE ride_requests (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    PASSENGER_ID BIGINT NOT NULL,

    PICKUP_LAT DOUBLE NOT NULL,
    PICKUP_LNG DOUBLE NOT NULL,
    PICKUP_GEOHASH VARCHAR(12) NOT NULL,

    DROP_LAT DOUBLE NOT NULL,
    DROP_LNG DOUBLE NOT NULL,
    DROP_GEOHASH VARCHAR(12) NOT NULL,

    SEATS_REQUIRED INT DEFAULT 1,
    LUGGAGE_COUNT INT DEFAULT 0,
    MAX_DETOUR_MINUTES INT NOT NULL,

    STATUS VARCHAR(20) NOT NULL,
    RIDE_ID BIGINT NULL,

    REQUEST_TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 0,

    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(ID),

    INDEX IDX_STATUS_GEOHASH (STATUS, PICKUP_GEOHASH),
    INDEX IDX_RIDE_ID (RIDE_ID)
)