CREATE TABLE RIDES (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    CAB_ID BIGINT NOT NULL,
    STATUS VARCHAR(20) NOT NULL,

    TOTAL_SEATS_USED INT DEFAULT 0,
    TOTAL_LUGGAGE_USED INT DEFAULT 0,

    ESTIMATED_TOTAL_TIME INT,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    VERSION BIGINT DEFAULT 0,

    FOREIGN KEY (CAB_ID) REFERENCES CABS(ID),

    INDEX IDX_RIDE_STATUS (STATUS)
)