CREATE TABLE RIDE_PASSENGERS (
    RIDE_ID BIGINT NOT NULL,
    PASSENGER_ID BIGINT NOT NULL,
    PICKUP_ORDER INT,
    DROP_ORDER INT,

    PRIMARY KEY (RIDE_ID, PASSENGER_ID),
    FOREIGN KEY (RIDE_ID) REFERENCES RIDES(ID),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(ID)
);
