CREATE TABLE PRICING_SNAPSHOTS (
    ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    RIDE_ID BIGINT,
    PASSENGER_ID BIGINT,
    BASE_FARE DOUBLE,
    SURGE_MULTIPLIER DOUBLE,
    DETOUR_PENALTY DOUBLE,
    FINAL_PRICE DOUBLE,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (RIDE_ID) REFERENCES RIDES(ID),
    FOREIGN KEY (PASSENGER_ID) REFERENCES PASSENGERS(ID)
);
