CREATE TABLE IDEMPOTENCY_KEYS (
    ID BIGINT PRIMARY KEY AUTO_INCREMENT,
    IDEMPOTENCY_KEY VARCHAR(100) NOT NULL UNIQUE,
    RIDE_REQUEST_ID BIGINT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
)