CREATE TABLE USER(
    ID BIGINT PRIMARY KEY AUTO_INCREMENT ,
    USERNAME VARCHAR(20) UNIQUE NOT NULL ,
    PASSWORD VARCHAR(30) NOT NULL ,
    ROLE VARCHAR(10) NOT NULL ,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ;